name: Lint Code

on: push

jobs:
  lint-code:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display stylelint.config.js
        run: cat stylelint.config.js
